@startuml

title __PCBUILDERAPPLICATION's Class Diagram__\n

'  namespace  {
    namespace ph.edu.dlsu.lbycpa2.pcbuilderapplication {
      class ph.edu.dlsu.lbycpa2.pcbuilderapplication.PCBuilderController {
          ~ allCPU : ArrayList<String>
          ~ allCase : ArrayList<String>
          ~ allCooler : ArrayList<String>
          ~ allGPU : ArrayList<String>
          ~ allMobo : ArrayList<String>
          ~ allPSU : ArrayList<String>
          ~ allRAM : ArrayList<String>
          ~ allStorage : ArrayList<String>
          ~ buildTotalPrice : double
          ~ casesSpecsLabel : String[]
          {static} ~ compatibilityMotherboard : String[]
          ~ compatibleCase : String
          ~ compatibleLengthGPU : int
          ~ compatibleQuantity : int
          ~ coolerSpecsLabel : String[]
          ~ cpuSpecsLabel : String[]
          ~ current : String
          ~ gpuSpecsLabel : String[]
          ~ iGLine : String
          ~ m2Compatible : String
          ~ moboRam : String
          ~ moboSpecsLabel : String[]
          ~ pcName : String
          ~ priceList : Stack<Double>
          ~ psuSpecsLabel : String[]
          ~ ramSpecsLabel : String[]
          ~ selectedParts : Stack<String>
          ~ stage : int
          ~ storageSpecsLabel : String[]
          ~ tdp : int[]
          ~ tempCost : double
          - auxPane : AnchorPane
          - caseImage : ImageView
          - caseLabel : Label
          - casePHP : Label
          - casePrice : Label
          - coolerImage : ImageView
          - coolerLabel : Label
          - coolerPHP : Label
          - coolerPrice : Label
          - costLabel : Label
          - costLabelPHP : Label
          - cpuImage : ImageView
          - cpuLabel : Label
          - cpuPHP : Label
          - cpuPrice : Label
          - endPane : AnchorPane
          - gpuImage : ImageView
          - gpuLabel : Label
          - gpuPHP : Label
          - gpuPrice : Label
          - mbImage : ImageView
          - mbLabel : Label
          - mbPHP : Label
          - mbPrice : Label
          - partImage : ImageView
          - partLabel : Label
          - partsList : ListView<String>
          - pcNameField : TextField
          - prevButton : Button
          - programPane : AnchorPane
          - psuImage : ImageView
          - psuLabel : Label
          - psuPHP : Label
          - psuPrice : Label
          - ramImage : ImageView
          - ramLabel : Label
          - ramPHP : Label
          - ramPrice : Label
          {static} - rates : double
          - specsList : ListView<String>
          - startPane : AnchorPane
          - storageImage : ImageView
          - storageLabel : Label
          - storagePHP : Label
          - storagePrice : Label
          - totalLabel : Label
          - totalPHP : Label
          + initialize()
          + onNextClick()
          + onPrevClick()
          - addCosts()
          - cases()
          - clearListViews()
          - cooler()
          - cpu()
          - defaultImage()
          - getCaseAndRamCompatibility()
          - getComponentCost()
          - getGPUCompatibility()
          - getMotherboardCompatibility()
          - getPSUCompatibility()
          - gpu()
          - initCase()
          - initCooler()
          - initGPU()
          - initMobo()
          - initPSU()
          - initRAM()
          - initStorage()
          - mobo()
          - onStartClick()
          - onStartOverClick()
          - psu()
          - ram()
          - setPartImage()
          - setSpecsList()
          - setTitles()
          - storage()
          - subtractPrevious()
      }
    }
'  }
  

  ph.edu.dlsu.lbycpa2.pcbuilderapplication.PCBuilderApplication -up-|> javafx.application.Application
  ph.edu.dlsu.lbycpa2.pcbuilderapplication.PCBuilderController .up.|> javafx.fxml.Initializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
